### ISSUE TITLE
Question about OOM in LongBench based on Qwen2-7B

### ISSUE THREAD

**Issue by MGDDestiny** [sail-sg/SimLayerKV#1]
Hello, I appreciate your KV Cache Eviction work not based on attention weights which often result in OOM.

So, how do you afford OOM when testing Qwen2-7B or any other models like this size using methods like H2O based on attention weights in Longbench testing(maxlen=31500)?

I always get a OOM error in 1 80G A800, very sad about this.

Thank you!

**Comment by jadeCurl** [comment]
Hi,

Thank you for your interest! Maybe you can try deleting the tensors and calling `torch.cuda.empty_cache()` at the appropriate time, as this could help.
